### ISSUE TITLE
Deploy Unifi Controller on an EC2 instance

### ISSUE THREAD

**Issue by KSiig** [KSiig/homelab#12]
Rather than the Unifi Controller being on an LXC container on Proxmox, it should be on an t2.micro EC2 instance on AWS.

It should be provisioned using Terraform and configured using Ansible.

**Comment by KSiig** [comment]
# Task list

- [ ] Provision with Terraform
- [ ] Configure ackup
- [ ] Configure Backup restore

**Comment by KasperSiig** [comment]
# Test

- [ ] This is a test
